version: "3"
services:
  dist-db:
    build:
      context: .
      dockerfile: Dockerfile-dist-db
    restart: always
    ports:
      - "5432:5432"
  prd-db:
    build:
      context: .
      dockerfile: Dockerfile-prd-db
    restart: always
    ports:
      - "5555:5432"
  dist-app:
    build:
      context: .
      dockerfile: Dockerfile-dist-app
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "/tmp/deployments:/opt/wildfly/standalone/deployments:rw"
    depends_on:
      - dist-db
      - prd-db